[book]
authors = ["Michael Chadwick"]
description = "Guide for the Ybixo programming language."
language = "en"
src = "src"
title = "The Ybixo Programming Language"

[output.html]
additional-js = ["js/highlight.min.js", "js/ybixo.min.js"]
cname = "www.ybixo.com"
edit-url-template = "https://github.com/michaelchadwick/ybixo-book/edit/main/{path}"
git-repository-url = "https://github.com/michaelchadwick/ybixo-book"
hash-files = true
